#!/bin/bash
set -e

# 将环境变量转换为 Wrangler 的本地变量文件 (.dev.vars)
# 这是为了让 wrangler dev 在 Docker 容器中能读取到 docker run -e 传入的变量
echo "# Auto-generated by docker-entrypoint.sh" > .dev.vars

# 1. 处理必填项 EPG_URL
if [ -z "$EPG_URL" ]; then
    echo "Error: EPG_URL environment variable is required."
    exit 1
else
    echo "EPG_URL=\"$EPG_URL\"" >> .dev.vars
fi

# 2. 处理可选配置项
# 定义需要导入的变量列表
OPTIONAL_VARS=(
  "EPG_URL_BACKUP"
  "CACHE_TTL"
  "FETCH_TIMEOUT"
  "MAX_MEMORY_CACHE_CHARS"
  "MAX_SOURCE_SIZE_BYTES"
  "ERROR_COOLDOWN_MS"
)

# 循环检查并写入
for var_name in "${OPTIONAL_VARS[@]}"; do
    var_value="${!var_name}" # 间接引用获取变量值
    if [ -n "$var_value" ]; then
        echo "$var_name=\"$var_value\"" >> .dev.vars
        echo "Imported config: $var_name"
    fi
done

echo "✅ Environment configured. Starting Worker..."

# 执行传入的命令 (即 Dockerfile 中的 CMD)
exec "$@"